/** @format */

import Head from 'next/head';
import { Container, Row } from 'react-bootstrap';
import IndexOrderTable from '../components/IndexOrderTable';
import data from '../getData';

export default function Home(): JSX.Element {
	const parsedData = JSON.parse(data);
	console.log(parsedData);
	return (
		<>
			<Head>
				<title>Example App</title>
				<meta
					name='description'
					content='Example app, Generated by create next app'
				/>
			</Head>
			<Container>
				<Row>
					<IndexOrderTable orders={parsedData} />
				</Row>
			</Container>
		</>
	);
}
