/** @format */

import Head from 'next/head';

export default function Home() {
	return (
		<>
			<Head>
				<title>Example App</title>
				<meta
					name='description'
					content='Example app, Generated by create next app'
				/>
			</Head>
		</>
	);
}
